# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: htop
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: wireguard

# geerlingguy.security
security_ssh_port: "{{ demo_ssh_port }}"
security_sudoers_passworded:
  - "{{ main_username }}"

# geerlingguy.ntp
ntp_timezone: "America/New_York"

# geerlingguy.docker
# defaults are sane, no need to configure anything
# https://github.com/geerlingguy/ansible-role-docker/blob/master/defaults/main.yml

# geerlingguy.github_users

github_users_authorized_keys_exclusive: true
github_users:
  # You can specify an object with 'name' (required) and 'groups' (optional):
  - name: "{{ main_username }}"
    groups: sudo,docker

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml " }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }
  - { alias: "appdata", command: "cd /mnt/tank/appdata" }
  - { alias: "zspace", command: "zfs list -o space" }
  - { alias: "zsnap", command: "zfs list -t snapshot" }

# ironicbadger.docker_compose_generator
appdata_path: "/home/{{ main_username }}/appdata"
containers:
  - service_name: traefik
    active: true
    image: traefik
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --log.level=debug
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      #- --certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      - "--certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}"
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
    volumes:
      - "{{ appdata_path }}/traefik/letsencrypt:/letsencrypt"
      - "{{ appdata_path }}/traefik/etc:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    include_global_env_vars: false
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
  - service_name: mysql_lychee
    active: true
    image: mariadb:10.5.5-focal
    container_name: mysql_lychee
    volumes:
      - "{{ appdata_path }}/mysql_lychee:/var/lib/mysql" 
    environment:
      - "MYSQL_ROOT_PASSWORD={{ mysql_root_password }}"
      - "MYSQL_PASSWORD={{ mysql_password }}"
      - "MYSQL_DATABASE={{ mysql_database_lychee }}"
      - "MYSQL_USER={{ mysql_user_lychee }}"
    include_global_env_vars: false
    restart: unless-stopped
  - service_name: lychee
    active: true
    image: lycheeorg/lychee:v4.0.6
    container_name: lychee
    volumes:
      - "{{ appdata_path }}/lychee/config:/config"
      - "{{ appdata_path }}/lychee/uploads:/uploads"
      - "{{ appdata_path }}/lychee/sym:/sym"
    environment:
      - PHP_TZ=America/New_York
      - DB_CONNECTION=mysql
      - DB_HOST=mysql_lychee
      - DB_PORT=3306
      - "DB_USERNAME={{ mysql_user_lychee }}"
      - "DB_DATABASE={{ mysql_database_lychee }}"
      - "DB_PASSWORD={{ mysql_password }}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.lychee.rule=Host(`gallery.selfhosted.show`)
      - traefik.http.routers.lychee.entrypoints=websecure
      - traefik.http.routers.lychee.tls.certresolver=cloudflare
      - traefik.http.services.lychee.loadbalancer.server.port=80
    depends_on:
      - mysql_lychee
    include_global_env_vars: false
    restart: unless-stopped