---
# ktz-figurine
figurine_name: jb-status

# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: htop
  - name: ncdu
  - name: net-tools
  - name: nmap
  - name: sanoid
  - name: sudo
  - name: tmux
  - name: tree
  - name: wget
  - name: wireguard
  - name: zfsutils-linux

# geerlingguy.security
security_ssh_port: "{{ demo_ssh_port }}"
security_sudoers_passwordless:
  - "{{ main_username }}"

# geerlingguy.ntp
ntp_timezone: "America/New_York"

# ironicbadger.bash-aliases (formerly ferrarimarco.bash-aliases)
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dstop", command: "docker stop `docker ps -aq`" }
  - { alias: "drm", command: "docker rm `docker ps -aq`" }
  - { alias: "dcp", command: "docker-compose -f ~/docker-compose.yml " }
  - { alias: "dprune", command: "docker image prune" }
  - { alias: "dprunesys", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }
  - { alias: "appdata", command: "cd /mnt/tank/appdata" }
  - { alias: "zspace", command: "zfs list -o space" }
  - { alias: "zsnap", command: "zfs list -t snapshot" }
  - { alias: "dfclean", command: "df -h -x tmpfs -t fuse.mergerfs -t xfs -t ext4 -t zfs"}

# ironicbadger.docker_compose_generator
global_env_vars:
  - "PUID={{ main_uid }}"
  - "PGID={{ main_gid }}"
  - "TZ={{ ntp_timezone }}"
appdata_path_zfs: /tank/appdata

containers:
  - service_name: traefik
    active: true
    image: traefik
    container_name: tr
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --log.level=info
      - --accesslog=false
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - "--certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}"
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - "{{ appdata_path_zfs }}/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    restart: unless-stopped
  ###
  - service_name: jb-uptimekuma
    active: true
    image: louislam/uptime-kuma:1
    labels:
      - traefik.enable=true
      - traefik.http.routers.uptimekuma.rule=Host(`status.jupiterbroadcasting.com`)
      - traefik.http.routers.uptimekuma.entrypoints=websecure
      - traefik.http.routers.uptimekuma.tls.certresolver=cloudflare
    volumes:
      - "{{ appdata_path_zfs }}/jb_uptimekuma:/app/data"
    restart: unless-stopped
  ###
  - service_name: ktz-healthchecks
    active: true
    image: linuxserver/healthchecks
    labels:
      - traefik.enable=true
      - traefik.http.routers.hc.rule=Host(`hc.{{ domain_cloud }}`)
      - traefik.http.routers.hc.entrypoints=websecure
      - traefik.http.routers.hc.tls.certresolver=cloudflare
    environment:
      - "SITE_ROOT=https://hc.{{ domain_cloud }}"
      - "SITE_NAME=KTZ Healthchecks"
      - ALLOWED_HOSTS=*
      - "SUPERUSER_EMAIL={{ gmail_address }}"
      - "SUPERUSER_PASSWORD={{ cloud_healthchecks_app_password}}"
      - REGENERATE_SETTINGS=True
      - "SECRET_KEY={{ cloud_healthchecks_secret_key }}"
      - REGISTRATION_OPEN=False
      - "PUSHOVER_API_TOKEN={{ pushover_api_healthchecks}}"
      - "PUSHOVER_SUBSCRIPTION_URL={{ pushover_healthchecks_subscription_url }}"
      - "TELEGRAM_BOT_NAME={{ hc_telegram_bot_name }}"
      - "TELEGRAM_TOKEN={{ hc_telegram_token }}"
    volumes:
      - "{{ appdata_path_zfs }}/ktz-healthchecks:/config"
    include_global_env_vars: true
    restart: unless-stopped  