---
- hosts: demo
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.github-users
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: ktz-figurine
    - role: ktz-boot-notification
    - role: ironicbadger.ansible_role_bash_aliases
    - role: ironicbadger.ansible_role_docker_compose_generator
      tags: compose
    - role: sanoid
  tasks:
    - hostname:
        name: jb-core

- hosts: status
  vars_files:
    - 'vars/vault.yaml'
  tasks:
  - hostname:
      name: jb-status
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.github-users
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: ktz-boot-notification
    - role: ironicbadger.figurine
    - role: ironicbadger.ansible_role_bash_aliases
    - role: ironicbadger.ansible_role_docker_compose_generator
      tags: compose
    - role: sanoid
