---
- hosts: core
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.github-users
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: ironicbadger.figurine
    - role: ktz-boot-notification
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.docker_compose_generator
      tags: compose
    - role: dns
      tags: compose
    - role: sanoid
  tasks:
    - hostname:
        name: jb-core

- hosts: dev
  vars_files:
    - 'vars/vault.yaml'
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.github-users
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: ironicbadger.figurine
    - role: ktz-boot-notification
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.docker_compose_generator
      tags: compose
    - role: dns
      tags: compose
    - role: sanoid
  tasks:
    - hostname:
        name: jb-dev

- hosts: status
  vars_files:
    - 'vars/vault.yaml'
  tasks:
  - hostname:
      name: jb-status
  roles:
    - role: grog.package
    - role: geerlingguy.docker
    - role: geerlingguy.github-users
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: ktz-boot-notification
    - role: ironicbadger.figurine
    - role: ironicbadger.bash_aliases
    - role: ironicbadger.docker_compose_generator
      tags: compose
    - role: sanoid
    - role: dns
      tags: dns
